import Listing from '../models/listing_model';

/*
listing_id (unique string generated by Mongo)
location_id (string from Locations)
host_user_id (string from Users)
users (JSON, in the form: [{user_id=123,is_confirmed=0},{user_id=456,is_confirmed=0}]
num_looking_for_game
start_time (UTC time when the game will start)
posted_time (UTC time when the listing was posted)
*/

export const createListing = (req, res) => {
  const listing = new Listing();
  listing.location_id = req.body.location_id;
  listing.host_user_id = req.body.host_user_id;
  listing.users = [req.body.host_user_id];
  listing.num_looking_for_game = req.body.num_looking_for_game;
  listing.start_time = req.body.start_time;
  listing.save()
  .then(result => {
    res.json({ message: 'Listing created!' });
  })
  .catch(error => {
    res.json({ error });
  });
};

export const getListings = (req, res) => {
  Location.find().sort('-location_name').exec((error, locations) => {
    res.json(locations.map(location => {
      return { location_id: location._id, location_name: location.location_name };
    }));
  });
};

export const removeListing = (req, res) => {

};

export const updateListing = (req, res) => {
  User.update({ _id: req.params.id }, {
    phone: req.body.phone,
    can_host: req.body.can_host,
    default_location_id: req.body.default_location_id,
  }, {}, (error, raw) => {
    if (error === null) {
      res.json({ message: 'User updated!' });
    } else {
      res.json({ error });
    }
  });
};

export const joinListing = (req, res) => {

};

export const leaveListing = (req, res) => {

};

export const confirmListing = (req, res) => {

};
